### ISSUE TITLE
Mac instructions

### ISSUE THREAD

**Issue by digionesntwos** [dradovic/SoundCloud4PS3#1]
Hi, Do you have instructions for the Mac version?  The instructions you have are for Windows based computers. I currently installed PS3 media server pms-macosx-1.10.5.dmg version.  Thanks.

**Comment by dradovic** [comment]
Hi, which part of the instructions didn't you understand? It's pretty generic. Note that you need a version >= 1.20.409-BETA as described.

**Comment by digionesntwos** [comment]
I dropped the soundcloud files in the plugins folder as directed, but when i open up ps3mp, click on general config, under the plugin system box below it does not show anything.

btw I did download the incorrect file the first time.  I am now using the compatible file 1.20.409

Thanks

**Comment by dradovic** [comment]
Are you able to install and load any other extension for the PMS?

**Comment by digionesntwos** [comment]
Havent tried anything else, I only wanted to run soundcloud on my PS3

**Comment by dradovic** [comment]
That's what I thought. However, I currently have not the slightest idea what your problem could be. So, in order to find out, we must first find out if it is a general plugin loading problem of the PMS for Macs. Therefore, it would be great if you could try and see if you can install any other plugin.

**Comment by koolburger** [comment]
Download latest build of PMS 1.21.1 from here http://ps3mediaserver.org/files/pms-macosx-1.21.1-RC1.dmg
Download the compiled build of the plugin from here https://github.com/dradovic/SoundCloud4PS3/zipball/master -> extract contents of .zip file to folder on desktop.
Go to Applications folder, locate PS3 Media Server app, rightclick (ctrl click) choose "Show Package Contents" from contextual menu. Navigate to folder "Contents" -> "Resources" -> "Java" -> "plugins" and copy all .jar files from desktop folder.

**Comment by dradovic** [comment]
Thanks for the instructions!!!

**Comment by koolburger** [comment]
my pleasure
